apiVersion: batch/v1
kind: Job
metadata:
  name: improved-job
  namespace: job-ns
spec:
  parallelism: 2 # Runs the 2 jobs parallely
  completions: 4 # Runs the job to completion 4 times. Combined with 'parallelism' property, it means that a total of 4 jobs will be run, with maximum of 2 being run parallel at the same time.
  activeDeadlineSeconds: 100
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: echo-date
    spec:
      containers:
        - name: echo
          image: cgr.dev/chainguard/busybox:latest
          command: ["date"]
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
      restartPolicy: Never
      securityContext:
        seccompProfile:
          type: RuntimeDefault
