# cnpg cluster with backups
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-with-backup-config
spec:
  instances: 2
  storage:
    size: 1Gi
  backup:
    barmanObjectStore:
      destinationPath: "gs://kubernetes-syed-cnpg-backups" # Name of the bucket where you want to store the backup
      googleCredentials:
        gkeEnvironment: true
    retentionPolicy: "30d"
  serviceAccountTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: cnpg-backups@kubernetes-syed.iam.gserviceaccount.com # `cnpg-backups` is the account name and `kubernetes-syed` is the project name
