# Custom resource from cnpg used to bring up a pg cluster. Reference: https://cloudnative-pg.io/documentation/1.22/cloudnative-pg.v1/#postgresql-cnpg-io-v1-Cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-minimal
spec:
  instances: 2
  storage:
    size: 1Gi
