apiVersion: v1
kind: Service
metadata:
  name: nginxs # Plural because it sets up DNS for each replica in the StatefulSet (e.g. nginx-0.nginxs.default.svc.cluster.local)
spec:
  type: ClusterIP
  clusterIP: None # This makes it a "headless" service. No IP is assigned as a common IP to all the replicas, each replica can be individually routed to. Run `kubectl get svc` and check.
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
