version: 3

env:
  VERSION: 0.23.2

tasks:
  # Deploying the trivy operator/controller as-is without any custom configuration. Reference: https://github.com/aquasecurity/trivy-operator
  01-install-trivy-operator:
    desc: "Install trivy operator into trivy-system namespace"
    cmds:
      - helm repo add aqua https://aquasecurity.github.io/helm-charts/
      - helm repo update
      - |
        helm upgrade --install trivy-operator aqua/trivy-operator \
          --namespace trivy-system \
          --create-namespace \
          --version ${VERSION}

  02-uninstall-trivy-operator:
    desc: "Uninstall the trivy operator"
    cmds:
      - helm uninstall trivy-operator --namespace trivy-system
