# This runs a cronjob, similar to how it works in linux. The schedule property defines how often this job is to run. The 'jobTemplate' property contains the
# specification that would be present in a normal job as CronJob makes use of Job internally, similar to how Deployment uses ReplicaSet.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-cronjob
spec:
  schedule: "* * * * *" # Refer the following link for more info on cron scheduling: https://crontab.guru
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: date-pod
              image: busybox:1.36.1
              command: ["date"]
          restartPolicy: Never
      backoffLimit: 1
