version: "3"

env:
  NAMESPACE: cronjob-ns

tasks:
  01-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}

  02-apply-cronjob:
    desc: "Apply the cronjob"
    cmds:
      - kubectl apply -f cronjob.yaml
    # To see the output of this pod, run `kubectl logs <pod-name>`

  03-create-job-from-cronjob:
    desc: "Manually create a job from a cronjob definition"
    cmds:
      - kubectl create job --from=cronjob/date-cronjob manual-job
    # This is typically used to manually run the job as per our convenience and testing purposes as waiting until the minute ends in quite tiresome.

  04-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - kubectl delete -f Namespace.yaml
