apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple-cluster
  namespace: service-ns
  labels:
    foo: deployment-label # Do not get confused and attempt to match with this
  annotations:
    bar: deployment-annotation # Do not get confused and attempt to match with this
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # This is the value you have to match to matchLabels above
      annotations:
        foo: pod-annotation # Do not get confused and attempt to match with this
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.0
