# This service allows you to access the containers from outside of the cluster and from your local system. Load balancing is performed accross the replicas

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    foo: service-label # Do not get confused and attempt to match with this
  annotations:
    bar: service-annotation # Do not get confused and attempt to match with this
spec:
  type: NodePort
  selector:
    app: nginx # This line should match the one defined in the labels section of deployment template
  ports:
    - protocol: TCP
      port: 80 # Port which this service is listening on
      targetPort: 80 # Port the container is listening on
      # nodePort: 30XXX (if unset, kubernetes will assign a port within 30000-32767)
