# Deployments are the most common resources you will use. Notice that the deployment has the same structure as the ReplicaSet.
# This is because internally ReplicaSet is used by Deployments. Deployments are used for stateless application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-improved-cluster
  namespace: deployment-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx # This should match the label you define below
  template:
    metadata:
      labels:
        app: nginx # Label which is matched to the deployment above
    spec:
      containers:
        - name: nginx
          image: cgr.dev/chainguard/nginx:1.27.0
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
