apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: app-ns
spec:
  type: ClusterIP
  selector:
    app: node-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
