# Build the docker image using the context of the current dir.
docker_build(
  'abdsyed/kubernetes-api-node', 
  './',
)
k8s_yaml('../../k8-deployment/api-node/components/deployment.yaml')
k8s_resource('node-service', port_forwards=3000)