# This is a role which will be applied accross the cluster and not just within a given namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader # There will be no name conflict between this and the normal Role as they are different kind of entities
rules:
  - apiGroups: [""]
    resources: ["pods"] # Only has access to pods
    verbs: ["get", "list", "watch"] # Can only get, list and watch pods
