# Bindin the cluster role we defined to a service account

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
  # List of users, groups or service accounts which will be mapped to this role
  - kind: ServiceAccount
    name: cluster-pod-reader
    namespace: rbac-ns
