# This job fetches all the pods running in a given namespace. To view the output run `kubectl logs <job-name>`

apiVersion: batch/v1
kind: Job
metadata:
  name: namespaced-pod-permissions-succeed
spec:
  template:
    spec:
      automountServiceAccountToken: true # Automounts the token of the service account
      containers:
        - name: kubectl
          image: cgr.dev/chainguard/kubectl
          args: ["get", "pods", "-n", "rbac-ns"]
      serviceAccountName: namespaced-pod-reader # Privileged service account
      restartPolicy: Never
  backoffLimit: 1
