# Simple pod which consumes the secrets
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.26.0
      volumeMounts:
        # Mounting the volume to /etc/config
        - name: secret-base64-data
          mountPath: /etc/config
      env:
        # Pulling just a single value from the secret. This will get converted to plaintext form when set as env var.
        - name: BASE64_SECRET
          valueFrom:
            secretKeyRef:
              name: base64-data # Notice that this maps to the name of the secret, not the volume!
              key: foo
        - name: STRING_SECRET
          valueFrom:
            secretKeyRef:
              name: string-data
              key: foo
  imagePullSecrets:
    # Not necessary since example uses a public image, but including to show how
    # you would use a registry credential secret to access a private image
    - name: dockerconfigjson
  volumes:
    # Similar to ConfigMap, we populate the volume with the data that we have defined in the Secret
    - name: secret-base64-data
      secret:
        secretName: base64-data
