version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: secrets-ns

tasks:
  01-create-namespace:
    desc: "Apply namespace and set as default"
    cmds:
      - kubectl apply -f namespace.yaml
      - kubens ${NAMESPACE}

  02-apply-secret-string-data:
    desc: "Apply Secret using string data"
    cmds:
      - kubectl apply -f secret-stringdata.yaml
    # View using `kubectl get secret`

  03-base64-encode:
    desc: "Base64 encode a string"
    cmds:
      - cmd: gum style "🚨 Be careful using 'echo' for this purpose since it includes a newline by default"
        silent: true
      - printf "base64-secret" | base64

  04-get-value:
    # You can repeat this for base64-data secret and get the same result, proving string data is encoded to base64 form.
    desc: "Get secret value"
    cmds:
      - kubectl get secret string-data -o yaml | yq '.data.foo'

  05-get-and-decode-value:
    # You can repeat this for base64-data secret and get the same result, proving string data is encoded to base64 form.
    desc: "Get secret value"
    cmds:
      - kubectl get secret string-data -o yaml | yq '.data.foo' | base64 -d

  06-apply-secret-base64-data:
    desc: "Apply secret using base64 data"
    cmds:
      - kubectl apply -f secret-base64.yaml

  07-create-dockerconfigjson:
    desc: "Create a Docker registry secret"
    cmds:
      - |
        kubectl create secret docker-registry dockerconfigjson \
          --docker-email=foo@bar.com \
          --docker-username=username \
          --docker-password=password \
          --docker-server=https://index.docker.io/v1/

  08-apply-dockerconfigjson:
    desc: "Apply a Docker registry secret configuration"
    cmds:
      - kubectl apply -f secret-dockerconfigjson.yaml

  09-apply-pod:
    desc: "Apply the pod"
    cmds:
      - kubectl apply -f pod.yaml

  10-exec-printenv:
    desc: "Check the properties consumed from configmap-property by running `printenv`"
    cmds:
      - kubectl exec secret-pod -c nginx -- printenv

  11-exec-cat-config:
    desc: "Check the foo file saved in /etc/config directory"
    cmds:
      - kubectl exec secret-pod -c nginx -- cat /etc/config/foo

  12-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - kubectl delete -f namespace.yaml
