# Loading custom ko builder
load('ext://ko', 'ko_build')
# building with ko
ko_build(
  'abdsyed/kubernetes-api-golang', 
  './',
  deps=['.']
)
# path to the deployment which consumes the image being built above
k8s_yaml('../../k8-deployment/api-golang/components/deployment.yaml')
# port forwarding so we can access it
k8s_resource('golang-api', port_forwards=8000)